nomeHtml = 'DANILO FERREIRA DE CÁSSIA'

corpo_email = (
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"'
    '"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">'
    '<html xmlns="http://www.w3.org/1999/xhtml">'
    '<head>'
    '    <title>Relatório de Execução</title>'
    '    <style type="text/css">'
    '        .tabela {'
    '            border-collapse: collapse;'
    '            width: 300px;'
    '        }'
    '        /* linhas pares (even) */'
    '        .tabela tbody tr:nth-child(even) {'
    '            background-color: #CCC;'
    '        }'
    '        /* linhas ímpares (odd) */'
    '        .tabela tbody tr:nth-child(odd) {'
    '            background-color: #FFF;'
    '        }'
    '    </style>'
    '</head>'
    '<body>'
    '    <table class="tabela">'
    '        <thead>'
    '	<tr>'
    '				<td><strong>Nome</strong></td>'
    '				<td><strong>Idade</strong></td>'
    '			</tr>'
    '		</thead>'
    '		<tbody>'
    '			<tr>'
    f'				<td>{nomeHtml}</td>'
    '				<td>29</td>'
    '			</tr>'
    '			<tr>'
    '				<td>Ricardo</td>'
    '				<td>30</td>'
    '			</tr>'
    '			<tr>'
    '				<td>Luiz</td>'
    '				<td>29</td>'
    '			</tr>'
    '			<tr>'
    '				<td>Ricardo</td>'
    '				<td>30</td>'
    '			</tr>'
    '			<tr>'
    '				<td>Luiz</td>'
    '				<td>29</td>'
    '			</tr>'
    '			<tr>'
    '				<td>Ricardo</td>'
    '				<td>30</td>'
    '			</tr>'
    '			<tr>'
    '				<td>Luiz</td>'
    '				<td>29</td>'
    '			</tr>'
    '			<tr>'
    '				<td>Ricardo</td>'
    '				<td>30</td>'
    '			</tr>'
    '			<tr>'
    '				<td>Luiz</td>'
    '				<td>29</td>'
    '			</tr>'
    '			<tr>'
    '				<td>Ricardo</td>'
    '				<td>30</td>'
    '			</tr>'
    '		</tbody>'
    '	</table>'
    '</body>'
    '</html>'
    )

arquivo = open('C:/teste/tabela.html', 'w', encoding='iso 8859-1')

arquivo.write(corpo_email)

